# Generated by Django 3.1.4 on 2020-12-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(max_length=50)),
                ('poll_description', models.CharField(blank=True, max_length=1000)),
                ('published', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='polls',
            field=models.ManyToManyField(related_name='questions', to='polls.Poll'),
        ),
    ]
