# Generated by Django 3.1.4 on 2020-12-08 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201208_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='polls',
        ),
        migrations.AddField(
            model_name='question',
            name='polls',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.poll'),
            preserve_default=False,
        ),
    ]
