# Generated by Django 3.1.4 on 2020-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201208_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('numeric_input', 'Numeric Input')], default='multiple_choice', max_length=50, verbose_name='Type of Question'),
        ),
    ]
