# Generated by Django 3.1.4 on 2020-12-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20201208_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='polls.choice'),
            preserve_default=False,
        ),
    ]
