# Generated by Django 3.1.4 on 2020-12-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20201208_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_type',
        ),
    ]
