# Generated by Django 3.1.4 on 2020-12-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20201208_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='numericchoice',
            name='choice_text',
            field=models.IntegerField(null=True),
        ),
    ]
