# Generated by Django 3.1.4 on 2020-12-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='question_type',
        ),
    ]
