# Generated by Django 3.1.4 on 2020-12-08 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20201208_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='numeric_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='polls.choice'),
        ),
    ]
