# Generated by Django 3.1.4 on 2020-12-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20201208_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='session_id',
            field=models.CharField(default=None, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
