# Generated by Django 3.1.3 on 2020-12-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_answer_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='session_id',
            field=models.CharField(max_length=500),
        ),
    ]
