# Generated by Django 3.1.3 on 2020-12-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20201209_0723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('session_id', 'question', 'poll')},
        ),
    ]
