# Generated by Django 3.1.3 on 2020-12-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20201209_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='value',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
