# Generated by Django 3.1.4 on 2020-12-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_choice_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('how_invest', models.TextField(blank=True)),
                ('motto', models.CharField(blank=True, max_length=500)),
                ('behavioral_biases', models.CharField(blank=True, max_length=200)),
                ('cognitive_biases', models.CharField(blank=True, max_length=200)),
                ('risk_value', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bits', to='polls.poll')),
            ],
        ),
    ]
