# Generated by Django 3.1.4 on 2020-12-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_bit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bit',
            name='poll',
        ),
        migrations.AddField(
            model_name='bit',
            name='poll',
            field=models.ManyToManyField(related_name='bits', to='polls.Poll'),
        ),
    ]
