# Generated by Django 3.1.4 on 2020-12-09 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20201209_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('aktien', models.FloatField(blank=True)),
                ('anleihen', models.FloatField(blank=True)),
                ('investment_horizon', models.FloatField(blank=True, default=0)),
                ('experience', models.FloatField(blank=True, default=0)),
                ('liquidity_needs', models.FloatField(blank=True, default=0)),
                ('bit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bits', to='polls.bit')),
            ],
        ),
    ]
