# Generated by Django 3.1.4 on 2020-12-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_sessionprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='total_score',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
