# Generated by Django 3.1.4 on 2020-12-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20201209_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='total_score',
        ),
    ]
