# Generated by Django 3.1.4 on 2020-12-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_remove_answer_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericchoice',
            name='choice_text',
            field=models.CharField(blank=True, default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionprofile',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
