# Generated by Django 3.1.4 on 2020-12-10 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20201210_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionprofile',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='polls.product'),
            preserve_default=False,
        ),
    ]
