# Generated by Django 3.1.4 on 2020-12-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20201210_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='polls',
            new_name='poll',
        ),
    ]
