# Generated by Django 3.1.4 on 2020-12-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20201210_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionprofile',
            name='profile_text',
        ),
    ]
