# Generated by Django 3.1.4 on 2020-12-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_remove_sessionprofile_profile_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionprofile',
            unique_together={('session_id', 'poll', 'product')},
        ),
    ]
