# Generated by Django 3.1.4 on 2020-12-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20201210_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.DateField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_input', to='polls.question')),
            ],
        ),
    ]
