# Generated by Django 3.1.4 on 2020-12-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_datechoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datechoice',
            old_name='choice_text',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('numeric_input', 'Numeric Input'), ('date_input', 'Date Input')], max_length=50, verbose_name='Type of Question'),
        ),
    ]
