# Generated by Django 3.1.4 on 2020-12-11 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_answer_date_answer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionprofile',
            unique_together={('session_id', 'poll')},
        ),
    ]
