# Generated by Django 3.1.4 on 2020-12-13 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_auto_20201211_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionprofile',
            name='product',
        ),
        migrations.AddField(
            model_name='sessionprofile',
            name='bit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='bit', to='polls.bit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='aktien',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='anleihen',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.RemoveField(
            model_name='product',
            name='bit',
        ),
        migrations.AddField(
            model_name='product',
            name='bit',
            field=models.ManyToManyField(related_name='bits', to='polls.Bit'),
        ),
    ]
