# Generated by Django 3.1.4 on 2020-12-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_auto_20201213_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionprofile',
            name='products',
            field=models.ManyToManyField(related_name='products', to='polls.Product'),
        ),
    ]
