# Generated by Django 3.1.4 on 2020-12-13 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_sessionprofile_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bit',
        ),
        migrations.AddField(
            model_name='product',
            name='bit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='polls.bit'),
            preserve_default=False,
        ),
    ]
